/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package intro;

public class App {


   
    public static int suma(int numero1, int numero2, int numero3){
        int resultado = numero1+numero2+numero3;
        return resultado;
    } 

    public static void main(String[] args) {
        int resultado = suma(5,6,7);
        System.out.println("el resultado es: "+ resultado);
        Coche coche = new Coche();
        coche.puertas = 3;
        coche.sumapuerta();

        System.out.println("el numero de puertas del coche es: "+ coche.puertas);

        
        
    }
        static class Coche{
        public int puertas = 4;
        public void sumapuerta(){
            puertas = puertas+1;
        }
        
    }
}
